<?php

namespace Okvpn\Bundle\MQInsightBundle\Entity\Repository;

/**
 * MQStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MQStateRepository extends \Doctrine\ORM\EntityRepository
{
}
