<?php

namespace Okvpn\Bundle\MQInsightBundle\Entity\Repository;

/**
 * ProcessorStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessorStatRepository extends \Doctrine\ORM\EntityRepository
{
}
